substitutions:
    device:
        id: doubleSensor
        name: "Double Sensor"
    config:
        sensor_1: 
            entityId: binary_sensor.occupancy 
            timeout: 60s
        sensor_2: 
            entityId: binary_sensor.occupancy 
            timeout: 60s
    output:
        id: output
        name: "Output"
        timeout: 30s
        icon: "mdi:sofa"



binary_sensor:
# ────────────────────────────────────────────────────────────────
# Input sensors imported from Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: homeassistant
    id: ${device.id}_occupancy_1
    entity_id: ${config.sensor_1.entityId}
    internal: true
    filters:
      - delayed_off: ${config.sensor_1.timeout}

  - platform: homeassistant
    id: ${device.id}_occupancy_2
    entity_id: ${config.sensor_2.entityId}
    internal: true
    filters:
      - delayed_off: ${config.sensor_2.timeout}
# ────────────────────────────────────────────────────────────────



# ────────────────────────────────────────────────────────────────
# Debug sensors exposed to Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: template
    id: ${device.id}_occupancy_debug_1
    device_id: ${device.id}
    name: "Occupancy Debug 1"
    device_class: occupancy
    entity_category: diagnostic
    lambda: |-
      if (id(${device.id}_occupancy_1).state == false) return false;
      if (id(${device.id}_occupancy_1).state == true) return true;
      return false;

  - platform: template
    id: ${device.id}_occupancy_debug_2
    device_id: ${device.id}
    name: "Occupancy Debug 2"
    device_class: occupancy
    entity_category: diagnostic
    lambda: |-
      if (id(${device.id}_occupancy_2).state == false) return false;
      if (id(${device.id}_occupancy_2).state == true) return true;
      return false;
# ────────────────────────────────────────────────────────────────



# ────────────────────────────────────────────────────────────────
# Virtual occupancy sensors exposed to Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: template
    id: ${output.id}
    device_id: ${device.id}
    name: "${output.name}"
    device_class: occupancy
    icon: ${output.icon}
    filters:
      - delayed_off: ${output.timeout}
    lambda: |-
      if (id(${device.id}_occupancy_1).state == true) return true;
      if (id(${device.id}_occupancy_2).state == true) return true;
      return false;
# ────────────────────────────────────────────────────────────────