substitutions:
    device:
        id: singleSensor
        name: "Single Sensor"
    config:
        sensorId: binary_sensor.occupancy
        sensorTimeOut: 60s
        debugInternal: 'true'
    output:
        id: output
        name: "Output"
        icon: "mdi:sofa"



binary_sensor:
# ────────────────────────────────────────────────────────────────
# Input sensors imported from Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: homeassistant
    id: ${device.id}_occupancy
    entity_id: ${config.sensorId}
    internal: true
    filters:
      - delayed_off: ${config.sensorTimeOut}
# ────────────────────────────────────────────────────────────────



# ────────────────────────────────────────────────────────────────
# Debug sensors exposed to Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: template
    id: ${device.id}_occupancy_debug
    device_id: ${device.id}
    name: "Occupancy Debug"
    device_class: occupancy
    entity_category: diagnostic
    internal: ${config.debugInternal}
    lambda: |-
      if (id(${device.id}_occupancy).state == false) return false;
      if (id(${device.id}_occupancy).state == true) return true;
      return false;
# ────────────────────────────────────────────────────────────────



# ────────────────────────────────────────────────────────────────
# Virtual occupancy sensors exposed to Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: template
    id: ${output.id}
    device_id: ${device.id}
    name: "${output.name}"
    device_class: occupancy
    icon: ${output.icon}
    lambda: |-
      if (id(${device.id}_occupancy).state == false) return false;
      if (id(${device.id}_occupancy).state == true) return true;
      return false;
# ────────────────────────────────────────────────────────────────