substitutions:
    device:
        id: singleSensor
    config:
        sensorId: binary_sensor.occupancy
        debugInternal: "true"
    output:
        icon: "mdi:sofa"

binary_sensor:
# ────────────────────────────────────────────────────────────────
# Input sensors imported from Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: homeassistant
    id: ${device.id}_occupancy
    entity_id: ${config.sensorId}
    internal: true
    filters:
      - delayed_off: ${device.id}_occupancy_output_timeout
    on_state_change: 
      then:
        - script.execute: ${device.id}_check_for_occupancy
        - binary_sensor.template.publish:
            id: ${device.id}_occupancy_debug
            state: !lambda 'return id(${device.id}_occupancy).state;'
# ────────────────────────────────────────────────────────────────



# ────────────────────────────────────────────────────────────────
# Debug sensors exposed to Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: template
    id: ${device.id}_occupancy_debug
    device_id: ${device.id}
    name: "Occupancy Debug"
    device_class: occupancy
    entity_category: diagnostic
    internal: ${config.debugInternal}
# ────────────────────────────────────────────────────────────────



# ────────────────────────────────────────────────────────────────
# Virtual occupancy sensors exposed to Home Assistant
# ────────────────────────────────────────────────────────────────
  - platform: template
    id: ${device.id}_occupancy_output
    device_id: ${device.id}
    name: "Occupancy"
    device_class: occupancy
    icon: ${output.icon}
# ────────────────────────────────────────────────────────────────

script:
  - id: ${device.id}_check_for_occupancy
    then: 
      - lambda: |-
          if (id(${device.id}_occupancy).state == true) {
            id(${device.id}_occupancy_output).publish_state(true);
            return;
          }

          id(${device.id}_occupancy_output).publish_state(false);

interval: 
  - id: ${device.id}_watchdog
    interval: 1min
    then: 
      - script.execute: ${device.id}_check_for_occupancy

number:
  - platform: template
    id: ${device.id}_occupancy_output_timeout
    name: "Timeout Occupancy"
    device_id: ${device.id}
    optimistic: true
    icon: mdi:timer-refresh-outline
    unit_of_measurement: "seconds"
    mode: "slider"
    min_value: 0
    max_value: 3600
    step: 15
    restore_value: true