substitutions:
  __esphome_pid_climate__: climate_name
  __ha_generic_thermostat__: climate.name
  __ha_sonoff_trv__: climate.name
  __interval__: 5s
  __internal__: "true"


packages:
  climate_package:
    url: https://github.com/S1146468/ESPHome-Packages
    files:
    - path: ImportClimateSensor.yaml
      vars:
        __device_name__: ${__ha_generic_thermostat__}
        __friendly_name__: "Generic Thermostat"
        __global_target__: temperature_setpoint
        __climate__: climate.name
        __script__: set_all_targets
        __interval__: 1s
        __internal__: "true"


