substitutions:
  __device_name__: device_name
  __esphome_pid_climate_friendly_name__: "Friendly name"
  __esphome_pid_climate__: climate_name
  __diagnostic_interval__: 30s
  __enable_error__: "false"
  __enable_multiplier__: "false"
  __enable_output_heat__: "false"
  __enable_output_cool__: "false"




sensor:
# ------------------------------- PID Error ------------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_error_raw
    type: ERROR  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_error
    name: "${__esphome_pid_climate_friendly_name__}: Error" 
    icon: "mdi:gauge"
    unit_of_measurement: "%"
    state_class: measurement
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_error_raw).state; 
    update_interval: ${__diagnostic_interval__} 
    internal: 
    - lambda: -|
        return !(${__enable_error__});
    entity_category: diagnostic







# --------------------------- PID Proportional ---------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_proportional_raw
    type: PROPORTIONAL  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_proportional
    name: "${__esphome_pid_climate_friendly_name__}: Error Proportional" 
    icon: "mdi:gauge"
    unit_of_measurement: "%"
    state_class: measurement
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_proportional_raw).state; 
    update_interval: ${__diagnostic_interval__}  
    internal: 
    - lambda: -|
        return !(${__enable_error__});
    entity_category: diagnostic







# ------------------------------ PID Integral ----------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_integral_raw
    type: INTEGRAL  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_integral
    name: "${__esphome_pid_climate_friendly_name__}: Error Integral" 
    icon: "mdi:gauge"
    unit_of_measurement: "%"
    state_class: measurement
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_integral_raw).state; 
    update_interval: ${__diagnostic_interval__}
    internal: 
    - lambda: -|
        return !(${__enable_error__});
    entity_category: diagnostic







# ----------------------------- PID Derivative ---------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_derivative_raw
    type: DERIVATIVE  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_derivative
    name: "${__esphome_pid_climate_friendly_name__}: Error Derivative" 
    icon: "mdi:gauge"
    unit_of_measurement: "%"
    state_class: measurement
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_derivative_raw).state; 
    update_interval: ${__diagnostic_interval__}  
    internal: 
    - lambda: -|
        return !(${__enable_error__});
    entity_category: diagnostic






# ------------------------------- PID Heat -------------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_heat_raw
    type: HEAT  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_heat
    name: "${__esphome_pid_climate_friendly_name__}: Output Heat" 
    unit_of_measurement: "%"
    icon: "mdi:gauge"
    state_class: measurement
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_heat_raw).state; 
    update_interval: ${__diagnostic_interval__} 
    internal: 
    - lambda: -|
        return !(${__enable_output_heat__});
    entity_category: diagnostic







# ------------------------------- PID Cool -------------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_cool_raw
    type: COOL  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_cool
    name: "${__esphome_pid_climate_friendly_name__}: Output Cool" 
    unit_of_measurement: "%"
    icon: "mdi:gauge"
    state_class: measurement
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_cool_raw).state; 
    update_interval: ${__diagnostic_interval__} 
    internal: 
    - lambda: -|
        return !(${__enable_output_cool__});
    entity_category: diagnostic







# -------------------------------- PID Kp --------------------------------- #
  - platform: pid
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_kp_raw
    type: KP  
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_kp
    name: "${__esphome_pid_climate_friendly_name__}: Multiplier Proportional (Kp)" 
    unit_of_measurement: ""
    icon: "mdi:gauge"
    state_class: measurement
    accuracy_decimals: 5
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_kp_raw).state; 
    update_interval: ${__diagnostic_interval__} 
    internal: 
    - lambda: -|
        return !(${__enable_multiplier__});
    entity_category: diagnostic







# -------------------------------- PID Ki --------------------------------- #
  - platform: pid     
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_ki_raw
    type: KI
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_ki
    name: "${__esphome_pid_climate_friendly_name__}: Multiplier Integral (Ki)" 
    unit_of_measurement: ""
    icon: "mdi:gauge"
    state_class: measurement
    accuracy_decimals: 5
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_ki_raw).state; 
    update_interval: ${__diagnostic_interval__} 
    internal: 
    - lambda: -|
        return !(${__enable_multiplier__});
    entity_category: diagnostic







# -------------------------------- PID Kd --------------------------------- #
  - platform: pid     
    climate_id: ${__esphome_pid_climate__}
    id: ${__device_name__}_${__esphome_pid_climate__}_kd_raw
    type: KD
    internal: True

  - platform: template
    id: ${__device_name__}_${__esphome_pid_climate__}_kd
    name: "${__esphome_pid_climate_friendly_name__}: Multiplier Derivative (Kd)" 
    unit_of_measurement: ""
    icon: "mdi:gauge"
    state_class: measurement
    accuracy_decimals: 5
    filters: 
      - clamp: 
          max_value: 100
          min_value: -100
          ignore_out_of_range: false
    lambda: |-
      return id(${__device_name__}_${__esphome_pid_climate__}_kd_raw).state; 
    update_interval: ${__diagnostic_interval__} 
    internal: 
    - lambda: -|
        return !(${__enable_multiplier__});
    entity_category: diagnostic