substitutions:
  deviceId: device
  tempSensor: sensor.temp

globals:
  - id: ${deviceId}_heater_value
    type: float
    restore_value: no
    initial_value: '0.0'
    
# Pull in a temperature sensor from Home Assistant
sensor:
  - platform: homeassistant
    entity_id: sensor.temp_sensor_room_stijn
    id: room_temp
    device_id: ${deviceId}

  - platform: template
    id: debug_output
    name: "Debug Output"
    device_id: ${deviceId}
    lambda: |-
      return id(${deviceId}_heater_value);
    update_interval: 1s

# Template output (acts like the heater/actuator)
output:
  - platform: template
    id: ${deviceId}_heater_output
    type: float
    write_action:
      - lambda: |-
          id(${deviceId}_heater_value) = x;

# PID Climate controller
climate:
  - platform: pid
    name: "PID Climate"
    sensor: room_temp
    default_target_temperature: 21 °C
    heat_output: ${deviceId}_heater_output
    # PID tuning parameters (adjust as needed)
    control_parameters:
      kp: 0.1
      ki: 0.02
      kd: 0.0