esphome:
  name: testdevice
  name_add_mac_suffix: false
  friendly_name: TestDevice


logger:
  level: WARN

esp32:
  board: esp32dev
  framework:
    type: arduino

ota: 
  - platform: esphome
    password: !secret ota_password

api:
  encryption:   
    key: !secret esphome-testdevice_Key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

