esphome:
  name: thermostat
  name_add_mac_suffix: false
  friendly_name: Thermostat


  devices:
    - id: climate_1
      name: "Climate 1"
      area_id: room_1   

    - id: climate_2
      name: "Climate 2"
      area_id: room_2

  areas:
    - id: room_1
      name: "Room 1"
    
    - id: room_2
      name: "Room 2"

esp32:
  board: esp32dev
  framework:
    type: arduino
    
# Enable logging
logger:
  level: info

# Example configuration entry
ota:
  - platform: esphome
    password: !secret ota_password

api:
  encryption:
    key: !secret thermostat_KEY

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: !secret thermostat_IP
    gateway: !secret gateway_IP
    subnet: !secret subnet
  ap:
    ssid: "Thermostat"
    password: ""

  domain: .local





substitutions:
  update_interval: 5s

packages:
  url: https://github.com/S1146468/ESPHome-Packages
  ref: main
  refresh: 0s
  files:

########################################################################################
# Opentherm 
########################################################################################
    - path: Thermostat/OpenTherm.yaml
      vars:
        outputId: t_set
        boiler_enable: boiler_enable
        boiler_active: boiler_active
        openthermPin:
          ot_in: 21
          ot_out: 22

########################################################################################
# Output Calculation
########################################################################################
    - path: Thermostat/ThermostatOutputCalculation.yaml
      vars:
        water_temp:
          min_temp: "40" 
          max_temp: "70"
        opentherm_update_interval: ${update_interval}
        output_entity_name: t_set
        boiler_enable: boiler_enable
        outside_temp_sensor: sensor.temperature
        pid_output:
          room_1: pid_output_1
          room_2: pid_output_2


########################################################################################
# Room Climate Devices
########################################################################################
    - path: Thermostat/ClimatePID/ClimateDevice.yaml
      vars:
        device:
          id: climate_1
          name: "Climate 1"
        climate:
          id: heating_1
          name: "Verwarming 1"
          pid_output: pid_output_1
          boiler_active: boiler_active
          interval: ${update_interval}
        control:
          pid:
            kp: 1.0 
            ki: 1.0 
            kd: 1.0 
          clamp: 
            i_min: 0.0
            i_max: 1.0
          averaging: 
            derivative: 10
            output: 1
          deadband:
            threshold: 
              low: "-0.30째C"
              high: "0.30째C"
            multiplier: 
              kp: 0.2
              ki: 0.25
              kd: 0.75
            averaging: 
              output: 28
        sensor:
          temperature: sensor.temperature_sensor_room_1
          humidity: sensor.humidity_sensor_room_1
          window: binary_sensor.window_contact_sensor_room_1
        master: climate.master_home_assistant_generic_thermostat_1


    - path: Thermostat/ClimatePID/ClimateDevice.yaml
      vars:
        device:
          id: climate_2
          name: "Climate 2"
        climate:
          id: heating_2
          name: "Heating 2"
          pid_output: pid_output_2
          boiler_active: boiler_active
          interval: ${update_interval}
        control:
          pid:
            kp: 1.0 
            ki: 1.0 
            kd: 1.0 
          clamp: 
            i_min: 0.0
            i_max: 1.0
          averaging: 
            derivative: 10
            output: 1
          deadband:
            threshold: 
              low: "-0.30째C"
              high: "0.30째C"
            multiplier: 
              kp: 0.2
              ki: 0.25
              kd: 0.75
            averaging: 
              output: 28
        sensor:
          temperature: sensor.temperature_sensor_room_2
          humidity: sensor.humidity_sensor_room_2
          window: binary_sensor.window_contact_sensor_room_2
        master: climate.master_home_assistant_generic_thermostat_2


########################################################################################
# Debug Sensors
########################################################################################
    - path: Thermostat/ClimatePID/ClimateDebugSensors.yaml
      vars:
        device:
          id: climate_1
          name: "Climate 1"
        climateId: heating_1
        disabled:                
          error: "false"
          multiplier: "false"
          heatOutput: "false"
          coolOutput: "true"
        updateInterval: ${update_interval}


    - path: Thermostat/ClimatePID/ClimateDebugSensors.yaml
      vars:
        device:
          id: climate_2
          name: "Climate 2"
        climateId: heating_2
        disabled:
          error: "false"
          multiplier: "false"
          heatOutput: "false"
          coolOutput: "true"
        updateInterval: ${update_interval}
          