substitutions:
  outputId: t_set
  opentherm:
    in_pin: "0"
    out_pin: "0"

####################################################################################################
# Enable OpenTherm communication
opentherm:
  in_pin: ${opentherm.in_pin} # WeMos D1 Mini ESP32 input pin for stacking with Master OpenTherm Shield
  out_pin: ${opentherm.out_pin} # WeMos D1 Mini ESP32 output pin for stacking with Master OpenTherm Shield


# Use switches to enable/disable central heating and hot water from HA interface
# https://esphome.io/components/opentherm.html#switch
switch:
  - platform: opentherm
    ch_enable:
      id: ch_enable
      name: "Heating"
      restore_mode: RESTORE_DEFAULT_ON
      internal: true
      entity_category: config

    dhw_enable:
      id: dhw_enable
      name: "Hot Water"
      restore_mode: RESTORE_DEFAULT_OFF
      internal: true
      entity_category: config


# Use numbers or outputs to control numerical values like CH/DHW setpoint from HA interface
# https://esphome.io/components/opentherm.html#numerical-values 
output:
  - platform: opentherm
    t_set:
      id: ${outputId}
      step: 0.5
      min_value: 0.0
      auto_max_value: true
      zero_means_zero: true

button:
  - platform: restart
    name: "Thermostaat restart"



# Use binary sensors (on/off) to monitor the states and conditions of different boiler entities.
# https://esphome.io/components/opentherm.html#binary-sensor
binary_sensor:
  - platform: opentherm
    ch_active:
      id: ch_active
      name: "Heating Active"

    dhw_active:
      id: dhw_active
      name: "Hot Water Active"

    flame_on:
      id: flame_on
      name: "Flame On"

    fault_indication:
      id: fault_indication
      name: "Boiler Fault"
      entity_category: diagnostic

    diagnostic_indication:
      id: diagnostic_indication
      name: "Boiler Diagnostic"
      entity_category: diagnostic

    electricity_production:
      id: electricity_production
      name: "Electricity production"
      entity_category: diagnostic

    service_request:
      name: Service Required
      entity_category: diagnostic

sensor:
- platform: wifi_signal
  name: "RSSI"
  id: sensor_rssi
  update_interval: 90s
  entity_category: "diagnostic"

- platform: uptime
  name: "Uptime"
  id: sensor_uptime
  update_interval: 300s
  entity_category: "diagnostic"

# OpenTherm sensors
# https://esphome.io/components/opentherm.html#sensor
- platform: opentherm
  t_boiler:
    id: ch_temperature
    name: "Heating Temperature"
    entity_category: diagnostic

  t_dhw:
    id: dhw_temperature
    name: "Hot Water Temperature"
    entity_category: diagnostic

  ch_pressure: 
    id: ch_pressure
    name: "Water pressure in CH circuit (bar)"
    entity_category: diagnostic

  burner_starts:  
    id: burner_starts
    name: "Number of starts burner"
    entity_category: diagnostic
    
  burner_operation_hours:  
    id: burner_operation_hours
    name: "Number of hours that burner is in operation"
    entity_category: diagnostic
    
  dhw_burner_operation_hours:  
    id: dhw_burner_operation_hours
    name: "Number of hours that burner is in operation during DHW mode"
    entity_category: diagnostic

  t_dhw_set:  
    id: t_dhw_set_
    name: "Hot Water Temperature Setpoint (°C)"
    entity_category: diagnostic