substitutions:
  outputId: t_set
  openthermPin:
    ot_in: 0
    ot_out: 0

####################################################################################################
# Enable OpenTherm communication
opentherm:
  in_pin: ${openthermPin.ot_in} # WeMos D1 Mini ESP32 input pin for stacking with Master OpenTherm Shield
  out_pin: ${openthermPin.ot_out} # WeMos D1 Mini ESP32 output pin for stacking with Master OpenTherm Shield
  before_process_response:
    then:
      - lambda: |-
          // 16-bit raw helper
          auto raw16 = (uint16_t(x.valueHB) << 8) | uint16_t(x.valueLB);
          auto fx88  = int16_t(raw16) / 256.0f;

          if (x.type == esphome::opentherm::MessageType::READ_ACK) {
            switch (x.id) {
              case 113:  // FAILED_BURNER_STARTS (U16)
                id(ot_failed_burner_starts).publish_state(raw16);
                break;
              case 114:  // BURNER_FLAME_LOW (U16)
                id(ot_burner_flame_low).publish_state(raw16);
                break;
              default:
                break;
            }
          }

# Use switches to enable/disable central heating and hot water from HA interface
# https://esphome.io/components/opentherm.html#switch
switch:
  - platform: opentherm
    ch_enable:
      id: ch_enable
      name: "Heating"
      restore_mode: RESTORE_DEFAULT_ON
      internal: true
      entity_category: config

    dhw_enable:
      id: dhw_enable
      name: "Hot Water"
      restore_mode: RESTORE_DEFAULT_OFF
      internal: true
      entity_category: config


# Use numbers or outputs to control numerical values like CH/DHW setpoint from HA interface
# https://esphome.io/components/opentherm.html#numerical-values 
output:
  - platform: opentherm
    t_set:
      id: ${outputId}
      step: 0.5
      min_value: 0.0
      auto_max_value: true
      zero_means_zero: true

button:
  - platform: restart
    name: "Thermostaat restart"



# Use binary sensors (on/off) to monitor the states and conditions of different boiler entities.
# https://esphome.io/components/opentherm.html#binary-sensor
binary_sensor:
  - platform: opentherm
    ch_active:
      id: ch_active
      name: "Heating Active"

    dhw_active:
      id: dhw_active
      name: "Hot Water Active"

    flame_on:
      id: flame_on
      name: "Flame On"

    fault_indication:
      id: fault_indication
      name: "Boiler Fault"
      entity_category: diagnostic

    diagnostic_indication:
      id: diagnostic_indication
      name: "Boiler Diagnostic"
      entity_category: diagnostic

    electricity_production:
      id: electricity_production
      name: "Electricity production"
      entity_category: diagnostic

    service_request:
      name: Service Required
      entity_category: diagnostic

sensor:
- platform: wifi_signal
  name: "RSSI"
  id: sensor_rssi
  update_interval: 90s
  entity_category: "diagnostic"

- platform: uptime
  name: "Uptime"
  id: sensor_uptime
  update_interval: 300s
  entity_category: "diagnostic"

# OpenTherm sensors
# https://esphome.io/components/opentherm.html#sensor
- platform: opentherm
  t_boiler:
    id: ch_temperature
    name: "Heating Temperature"
    entity_category: diagnostic

  ch_pressure: 
    id: ch_pressure
    name: "Water pressure in CH circuit (bar)"
    entity_category: diagnostic

  rel_mod_level:
    id: rel_mod_level
    name: "Relative Modulation Level (%)"
    entity_category: diagnostic
    
  burner_starts:  
    id: burner_starts
    name: "Number of starts burner"
    entity_category: diagnostic
    
  burner_operation_hours:  
    id: burner_operation_hours
    name: "Number of hours that burner is in operation"
    entity_category: diagnostic
    
  dhw_burner_operation_hours:  
    id: dhw_burner_operation_hours
    name: "Number of hours that burner is in operation during DHW mode"
    entity_category: diagnostic

  t_ret:
    id: t_ret
    name: "Return Water Temperature"
    entity_category: diagnostic

- platform: template
  name: "OT Failed burner starts"
  id: ot_failed_burner_starts
  entity_category: diagnostic

- platform: template
  name: "OT Burner flame low"
  id: ot_burner_flame_low
  entity_category: diagnostic


